server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://app:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /register {
        proxy_pass http://app:8080/register;
        proxy_set_header Host $host;
    }

    location /login {
        proxy_pass http://app:8080/login;
        proxy_set_header Host $host;
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }

    location /welcome {
        proxy_pass http://app:8080/welcome;
        proxy_set_header Host $host;
    }
}
